"""empty message

Revision ID: 0923b14bbe85
Revises: 44b26824a55c
Create Date: 2023-08-04 19:17:52.721707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0923b14bbe85'
down_revision = '44b26824a55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('talent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('talent')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
