"""empty message

Revision ID: 5ea42a77ff62
Revises: 1de11602fd52
Create Date: 2023-08-06 20:17:12.124712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea42a77ff62'
down_revision = '1de11602fd52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
